# docker-compose.yml
version: '3.8'

x-common-env: &common-env
  HONEYCOMB_API_KEY:
  HONEYCOMB_DATASET:
  HONEYCOMB_API:
  OTEL_EXPORTER_OTLP_ENDPOINT:
  OTEL_EXPORTER_OTLP_HEADERS:
  OTEL_RESOURCE_ATTRIBUTES: app.running-in=docker
  MESSAGE_ENDPOINT: http://message:9000
  NAME_ENDPOINT: http://name:8000
  YEAR_ENDPOINT: http://year:6001

services:
  year:
    build: .
    ports:
      - "6001:6001"
    volumes:
      - .:/app
    environment:
      <<: *common-env
    # Mounts the source code into the container, allowing live updates
    # Development environment variables

