# Gemfile
source 'https://rubygems.org'

gem 'sinatra'
gem 'json'
gem 'net-http'
gem 'open-uri'
gem 'mini_magick'
gem 'rack'
gem 'rackup'
gem 'opentelemetry-sdk'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-instrumentation-all'
