# Gemfile
source 'https://rubygems.org'

gem 'sinatra'
gem 'json'
gem 'securerandom'
gem 'rack'
gem 'rackup'
gem 'opentelemetry-sdk'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-instrumentation-all'
