version: "2.4"

x-common-env: &common-env
  OTEL_EXPORTER: otlp
  OTEL_EXPORTER_OTLP_ENDPOINT: https://api.honeycomb.io
  OTEL_EXPORTER_OTLP_HEADERS:
  OTEL_SERVICE_NAME: year-service
  OTEL_RESOURCE_ATTRIBUTES: app.running-in=docker
  YEAR_ENDPOINT: http://year:6001

services:
  year:
    build: ./year-service
    image: hnyexample/year-ruby
    environment:
      <<: *common-env
    ports:
      - 6001:6001
